config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to:'static#home'
  
end

app/models/admin_user.rb
class AdminUser < User
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    
    belongs_to :user
    validates_presence_of :date, :rationale
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :posts
  validates_presence_of :first_name, :last_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :authenticate_user!
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only:[:show]
    
    def index
        
    end
    
    def new
        @post = Post.new
    end
    
    def create
        @post = Post.new(post_params)
        @post.user_id = current_user.id
        if @post.save
            redirect_to @post, notice: 'Your post was created succefully'
    else
        render 'new'
        end
    end
    def show
        @post = Post.find(params[:id])
    end


private
    def post_params
        params.require(:post).permit(:date, :rationale)
    end
    
    def set_post
        @post = Post.find(params[:id])
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    def home
    
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.erb
<footer id="foot" class="container-fluid">
        <div class="row">
            <div class="col-md-4 col-sm-6 footer-navigation">
                <h3><a href="#">Company<span>logo </span></a></h3>
                <p class="links"><a href="#">Home</a><strong> · </strong><a href="#">Blog</a><strong> · </strong><a href="#">Pricing</a><strong> · </strong><a href="#">About</a><strong> · </strong><a href="#">Faq</a><strong> · </strong><a href="#">Contact</a></p>
                <p class="company-name">Company Name © 2015 </p>
            </div>
            <div class="col-md-4 col-sm-6 footer-contacts">
                <div><span class="fa fa-map-marker footer-contacts-icon"> </span>
                    <p><span class="new-line-span">21 Revolution Street</span> Paris, France</p>
                </div>
                <div><span class="fa fa-phone footer-contacts-icon"></span>
                    <p class="footer-center-info email text-left"> +1 555 123456</p>
                </div>
                <div><span class="fa fa-envelope footer-contacts-icon"></span>
                    <p> <a href="#" target="_blank">support@company.com</a></p>
                </div>
            </div>
            <div class="clearfix visible-sm-block"></div>
            <div class="col-md-4 footer-about">
                <h4>About the company</h4>
                <p> Lorem ipsum dolor sit amet, consectateur adispicing elit. Fusce euismod convallis velit, eu auctor lacus vehicula sit amet.
                </p>
                <div class="social-links social-icons"><a href="#"><span class="fa fa-facebook"></span></a><a href="#"><span class="fa fa-twitter"></span></a><a href="#"><span class="fa fa-linkedin"></span></a><a href="#"><span class="fa fa-github"></span></a></div>
            </div>
        </div>
    </footer>

app/views/layouts/_header.html.erb
<div class="container">

      <header class="masthead">
        <h3 class="text-muted">Overtime</h3>

        <nav class="navbar navbar-expand-md navbar-grey bg-light rounded mb-3">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav text-md-center nav-justified w-100">
              <li class="nav-item active">
                <%= link_to "Home", root_path %>
              </li>
              <li class="nav-item">
                <%= link_to "Timestamps", posts_path %>
              </li>
             
              <li class="nav-item">
            <!--<a class="nav-link" href="#">Account</a>-->
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Account</a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Login</a>
                <%= link_to "Logout", destroy_user_session_path, method: :delete %>
            <!--<a class="dropdown-item" href="#">Something else here</a>-->
              <div class="dropdown-divider"></div>
                <%= link_to "Edit Account" , edit_user_registration_path %>
            </div>
            </li>
          </li>
             
             <!-- <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <a class="dropdown-item" href="#">Something else here</a>
                </div>-->
              </li>
            </ul>
          </div>
        </nav>
      </header>

      <main role="main">

<!-- Main jumbotron for a primary marketing message or call to action -->

      <div class="jumbotron">
        <div class="container">
          <h1>Welcome to the Overtime App!</h1>
          <!--<p>This is a template for a simple marketing or informational website. 
          It includes a large callout called a jumbotron and three supporting pieces 
          of content. Use it as a starting point to create something more unique.</p>-->
          <!--<a class="btn btn-primary btn-lg">Learn More &raquo;</a>-->
          <div align="center">
          <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
          </div>
        </div>
      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Overtime</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container-fluid">
    <%= render 'layouts/header' %>
    <%= render 'shared/alerts' %>
    <%= yield %>
    <div>
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<h2>Posts</h2>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>

<%= f.date_field :date%>
<%= f.text_area :rationale %>
<%= f.submit 'Save' %>
<% end %>

app/views/posts/show.html.erb
<%= @post.inspect %>

app/views/shared/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>